pipeline {
    agent any 
    stages {
        stage('Build') {
            steps {
                echo 'CHANGE_TITLE: ' + env.CHANGE_TITLE
                catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                    cd tests/ci/android/AWSLCAndroidTestRunner
                    mkdir apk-artifacts
                    ./gradlew assembleDebug assembleAndroidTest
                    mv app/build/outputs/apk apk-artifacts/non-fips-dbg
                    ./gradlew clean assembleDebug assembleAndroidTest -PRelease
                    mv app/build/outputs/apk apk-artifacts/non-fips-rel
                    ./gradlew clean assembleDebug assembleAndroidTest -PFIPS
                    mv app/build/outputs/apk apk-artifacts/fips
                    ls apk-artifacts
                }
            }
        }
    }
}
